name: healthos

services:

  postgres:
    image: postgres:17

    container_name: healthos-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: healthos
      POSTGRES_USER: healthos
      POSTGRES_PASSWORD: healthos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthos"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4

    container_name: healthos-pgadmin

    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@healthos-app.com
      PGADMIN_DEFAULT_PASSWORD: HealthOS_Admin_2026

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy

volumes:

  postgres_data: